"""Create Analysis table

Revision ID: 904fcdede22a
Revises: 6f21f87a2a23
Create Date: 2026-07-05 13:10:08.234128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904fcdede22a'
down_revision = '6f21f87a2a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
