"""Create Analysis table

Revision ID: ed14818b34cd
Revises: 904fcdede22a
Create Date: 2026-07-05 13:15:00.957466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed14818b34cd'
down_revision = '904fcdede22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('missing_skills', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('interview_questions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('learning_roadmap', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('project_ideas', sa.Text(), nullable=False))
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('project_ideas')
        batch_op.drop_column('learning_roadmap')
        batch_op.drop_column('interview_questions')
        batch_op.drop_column('missing_skills')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
